sudo: required
language: bash
services:
  - docker

env:
  global:
    - IMG=biggis/flink:1.4.0
    - RANCHER_ENV=cluster
    - RANCHER_STACK=flink

install:
  #login to dockerhub
  - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD

script:
  #build the images
  - docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF=`git rev-parse --short HEAD` -t $IMG .

after_success:
  - echo "build successful"
  #push the image to dockerhub
  - docker push $IMG
  #deploy to Rancher
  - docker run -ti --rm cdrx/rancher-gitlab-deploy:latest --rancher-url $RANCHER_URL --rancher-key $RANCHER_ACCESS_KEY --rancher-secret $RANCHER_SECRET_KEY --environment $RANCHER_ENV --stack $RANCHER_STACK --service flink-jobmanager --new-image $IMG --finish-upgrade
  - docker run -ti --rm cdrx/rancher-gitlab-deploy:latest --rancher-url $RANCHER_URL --rancher-key $RANCHER_ACCESS_KEY --rancher-secret $RANCHER_SECRET_KEY --environment $RANCHER_ENV --stack $RANCHER_STACK --service flink-taskmanager --new-image $IMG --finish-upgrade
