version: '2'
services:

  flink-jobmanager:
    image: biggis/flink:1.3.0
    hostname: flink-jobmanager
    ports:
      - "8081:8081"
      - "6123:6123"
    command: start.sh jobmanager
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: flink_jobmanager=true
    environment:
      JOB_MANAGER_RPC_ADDRESS: flink-jobmanager.flink
      USER_ID: 1000
      USER_NAME: flink

  flink-taskmanager:
    image: biggis/flink:1.3.0
    hostname: flink-taskmanager
    depends_on:
      - jobmanager
    command: start.sh taskmanager
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
    environment:
      JOB_MANAGER_RPC_ADDRESS: flink-jobmanager.flink
      USER_ID: 1000
      USER_NAME: flink
