version: '2.1'
services:

  flink-jobmanager:
    image: biggis/flink:1.5.0
    hostname: flink-jobmanager
    ports:
      - "8081:8081"
      - "6123:6123"
    command: start.sh jobmanager
    environment:
      JOB_MANAGER_RPC_ADDRESS: flink-jobmanager
      HADOOP_MASTER_ADDRESS: hdfs-name.storage
      USER_ID: ${USER_ID-1000}
      USER_NAME: flink
      TIMEZONE: Europe/Berlin

  flink-taskmanager:
    image: biggis/flink:1.5.0
    hostname: flink-taskmanager
    depends_on:
      - flink-jobmanager
    command: start.sh taskmanager
    links:
      - "flink-jobmanager:flink-jobmanager"
    environment:
      JOB_MANAGER_RPC_ADDRESS: flink-jobmanager
      HADOOP_MASTER_ADDRESS: hdfs-name.storage
      USER_ID: ${USER_ID-1000}
      USER_NAME: flink
      TIMEZONE: Europe/Berlin
