version: '2.1'
services:

  jobmanager:
    image: biggis/flink:1.2.0
    hostname: jobmanager
    ports:
      - "8081:8081"
      - "6123:6123"
    command: docker-entrypoint.sh jobmanager
    environment:
      JOB_MANAGER_RPC_ADDRESS: jobmanager
      USER_ID: ${USER_ID-1000}
      USER_NAME: flink

  taskmanager:
    image: biggis/flink:1.2.0
    hostname: taskmanager
    depends_on:
      - jobmanager
    command: docker-entrypoint.sh taskmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      JOB_MANAGER_RPC_ADDRESS: jobmanager
      USER_ID: ${USER_ID-1000}
      USER_NAME: flink
